version: '3'
services:
  mongo:
    image: mongo:3.4.11
    container_name: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - /root/realworld/mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456
